import { Game } from '../services/games/games.service';

export const initalGames: Game[] = [
  {
    id: '0495b02a-970d-4544-8185-a41d790cebf8',
    title: 'Stronghold',
    description:
      'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    releaseDate: '2004-02-08',
    image: 'http://dummyimage.com/125x152.png/dddddd/000000',
    rating: 4,
    downloads: 5120,
    comingSoon: false,
  },
  {
    id: '5648e632-3688-4033-9ea7-5880e450b79a',
    title: 'Overhold',
    description:
      'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    releaseDate: '2001-11-22',
    image: 'http://dummyimage.com/207x125.png/cc0000/ffffff',
    rating: 4,
    downloads: 8655,
    comingSoon: false,
  },
  {
    id: '395c6aec-cdbe-452e-8d8d-58a1ba92af0d',
    title: 'Zathin',
    description: 'Fusce consequat. Nulla nisl. Nunc nisl.',
    releaseDate: '2023-07-22',
    image: 'http://dummyimage.com/235x201.png/cc0000/ffffff',
    rating: 1,
    downloads: 6202,
    comingSoon: false,
  },
  {
    id: '702ce2fa-3ead-4bcc-b460-6453de9ece7a',
    title: 'Voltsillam',
    description:
      'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    releaseDate: '2028-09-13',
    image: 'http://dummyimage.com/202x206.png/ff4444/ffffff',
    rating: 1,
    downloads: 9431,
    comingSoon: false,
  },
  {
    id: 'bf81a7b2-40f8-4f3d-8bf0-54b1d46b6826',
    title: 'Wrapsafe',
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    releaseDate: '2028-03-07',
    image: 'http://dummyimage.com/232x244.png/ff4444/ffffff',
    rating: 1,
    downloads: 6927,
    comingSoon: true,
  },
  {
    id: '7c9996e4-d09a-4ab5-b117-c35ad9333398',
    title: 'Fixflex',
    description:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    releaseDate: '2027-11-01',
    image: 'http://dummyimage.com/146x140.png/ff4444/ffffff',
    rating: 2,
    downloads: 2490,
    comingSoon: false,
  },
  {
    id: '18a6d5a4-3b88-4702-9972-97ac156d2763',
    title: 'It',
    description: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
    releaseDate: '2001-08-02',
    image: 'http://dummyimage.com/124x204.png/ff4444/ffffff',
    rating: 3,
    downloads: 549,
    comingSoon: false,
  },
  {
    id: 'bf3b539f-dcdd-49d3-8cee-c0227728b699',
    title: 'Kanlam',
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    releaseDate: '2019-07-14',
    image: 'http://dummyimage.com/122x108.png/ff4444/ffffff',
    rating: 2,
    downloads: 1682,
    comingSoon: false,
  },
  {
    id: '1561cef7-f83e-441f-862b-76d3f7b12afb',
    title: 'Span',
    description:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.',
    releaseDate: '2021-07-04',
    image: 'http://dummyimage.com/237x224.png/ff4444/ffffff',
    rating: 1,
    downloads: 151,
    comingSoon: false,
  },
  {
    id: '5a210b41-5bb0-438d-8565-56101ad0466a',
    title: 'Redhold',
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    releaseDate: '2029-10-06',
    image: 'http://dummyimage.com/244x224.png/dddddd/000000',
    rating: 4,
    downloads: 6208,
    comingSoon: true,
  },
  {
    id: '16a3f14c-041d-441b-a704-4d5692cccf02',
    title: 'Redhold',
    description:
      'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    releaseDate: '2012-09-26',
    image: 'http://dummyimage.com/226x129.png/5fa2dd/ffffff',
    rating: 3,
    downloads: 5632,
    comingSoon: false,
  },
  {
    id: '63fcd814-ffe9-4df6-b18f-e03087c42560',
    title: 'Domainer',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    releaseDate: '2009-01-23',
    image: 'http://dummyimage.com/166x226.png/cc0000/ffffff',
    rating: 4,
    downloads: 6471,
    comingSoon: false,
  },
  {
    id: '45316dad-6e93-4d3d-8201-21800837f37d',
    title: 'Bytecard',
    description:
      'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    releaseDate: '2029-08-03',
    image: 'http://dummyimage.com/227x240.png/ff4444/ffffff',
    rating: 4,
    downloads: 5947,
    comingSoon: true,
  },
  {
    id: '4fb161a3-b521-447a-8b84-365baec12799',
    title: 'Overhold',
    description:
      'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    releaseDate: '2014-11-09',
    image: 'http://dummyimage.com/184x122.png/5fa2dd/ffffff',
    rating: 5,
    downloads: 6753,
    comingSoon: false,
  },
  {
    id: 'd009f5be-1790-4dc5-bd09-76333cbf4268',
    title: 'Fixflex',
    description:
      'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
    releaseDate: '2019-02-23',
    image: 'http://dummyimage.com/176x146.png/ff4444/ffffff',
    rating: 4,
    downloads: 2213,
    comingSoon: false,
  },
  {
    id: '5f5f46c5-a2b9-4881-8bf2-6289a7e5788b',
    title: 'Domainer',
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    releaseDate: '2011-01-11',
    image: 'http://dummyimage.com/165x219.png/5fa2dd/ffffff',
    rating: 2,
    downloads: 9241,
    comingSoon: true,
  },
  {
    id: '2c14089f-a177-48d8-913f-8f3c7997eedb',
    title: 'Bitchip',
    description:
      'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    releaseDate: '2022-11-21',
    image: 'http://dummyimage.com/235x113.png/ff4444/ffffff',
    rating: 4,
    downloads: 9922,
    comingSoon: false,
  },
  {
    id: '67d51042-5c9e-48a4-b339-2a3dfaa15c85',
    title: 'Regrant',
    description:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
    releaseDate: '2025-12-08',
    image: 'http://dummyimage.com/208x146.png/dddddd/000000',
    rating: 2,
    downloads: 7454,
    comingSoon: false,
  },
  {
    id: '38dd9e7b-807f-4d59-ad68-3af3514f992a',
    title: 'Prodder',
    description:
      'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    releaseDate: '2014-07-21',
    image: 'http://dummyimage.com/130x146.png/cc0000/ffffff',
    rating: 5,
    downloads: 8231,
    comingSoon: false,
  },
  {
    id: 'a7e253f4-8cef-4e21-a758-a4ad20957cc5',
    title: 'Sonair',
    description:
      'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    releaseDate: '2013-01-12',
    image: 'http://dummyimage.com/203x116.png/cc0000/ffffff',
    rating: 2,
    downloads: 6794,
    comingSoon: true,
  },
];
